## Before using, change permissions to make executable with chmod

## Define the shell
#PBS -S /bin/bash

## Name the job
#PBS -N test_FASTQC

## Request resources
#PBS -l walltime=2:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb

## Specify the standard output file (rather than printing to screen)
#PBS -o /home/mleukam/fastqoutput.log

## Specify the standard error (rather than printing to screen)
#PBS -e /home/mleukam/fastqerror.log

# navigate to shell dir
cd /home/mleukam/shell

# call shell scrpt
./mlfastqc.sh

# exit code
exit 0