## Before using, change permissions to make executable with chmod

## Define the shell
#PBS -S /bin/bash

## Name the job
#PBS -N gatk_index

## Request resources
#PBS -l walltime=4:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb

## Specify the standard output file (rather than printing to screen)
#PBS -o /home/mleukam/gatkindexoutput.log

## Specify the standard error (rather than printing to screen)
#PBS -e /home/mleukam/gatkindexerror.log

# navigate to shell dir
cd /home/mleukam/shell

# call shell scrpt
./mlgatkindex.sh

# exit code
exit 0
