#!/bin/bash

###############################
## PBS RUN SCRIPT FOR FASTQC ##
###############################

## Define the shell
#PBS -S /bin/bash

## Name the job
#PBS -N Kallisto_index

## Request resources
#PBS -l walltime=12:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb

## Specify the merged error and standard output file
#PBS -j oe
#PBS -o /home/mleukam/logs/kallistoindex.log

# Navigate to shell dir
cd /home/mleukam/shell

## File variables passed as arguments through the qsub command that invokes this script
## Call shell scrpt
./kallistoindex.sh

# exit
exit 0